#line 2 "src/flex.c"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 58
#define YY_END_OF_BUFFER 59
static yyconst short int yy_acclist[225] =
    {   0,
       59,   57,   58,   56,   57,   58,   55,   58,   44,   57,
       58,   57,   58,   57,   58,   36,   57,   58,   40,   57,
       58,   57,   58,   45,   57,   58,   46,   57,   58,   39,
       57,   58,   34,   57,   58,   26,   57,   58,   35,   57,
       58,   51,   57,   58,   41,   57,   58,    3,    6,   57,
       58,    3,   57,   58,   25,   57,   58,   28,   57,   58,
       33,   57,   58,   27,   57,   58,   24,   57,   58,   49,
       57,   58,   50,   57,   58,   24,   57,   58,   24,   57,
       58,   24,   57,   58,   24,   57,   58,   24,   57,   58,
       24,   57,   58,   24,   57,   58,   24,   57,   58,   24,

       57,   58,   24,   57,   58,   47,   57,   58,   57,   58,
       48,   57,   58,   32,    8,   42,    5,   37,   38,   52,
        4,    1,    4,    6,    4,    3,   30,   31,   29,   24,
       24,   24,   24,   24,   24,   24,   24,   16,   24,   24,
       24,   24,   24,   24,   24,   43,    8,    5,    4,    4,
        1,    4,    4,    4,    4,    7,   24,   24,   24,   24,
       24,   24,   19,   24,   12,   24,   24,   24,   24,   24,
       24,    4,    4,    2,    4,    4,   24,   14,   24,   24,
       24,   17,   24,   24,   24,   24,   24,   24,   11,   24,
       24,    7,   20,   24,    9,   24,   24,   24,   13,   24,

       24,   24,   24,   18,   24,    7,    7,    7,   24,   10,
       24,   15,   24,   23,   24,   24,   54,    7,   24,   22,
       24,   53,   21,   24
    } ;

static yyconst short int yy_accept[182] =
    {   0,
        1,    1,    1,    2,    4,    7,    9,   12,   14,   16,
       19,   22,   24,   27,   30,   33,   36,   39,   42,   45,
       48,   52,   55,   58,   61,   64,   67,   70,   73,   76,
       79,   82,   85,   88,   91,   94,   97,  100,  103,  106,
      109,  111,  114,  115,  115,  116,  116,  116,  116,  117,
      117,  118,  118,  119,  120,  121,  122,  122,  123,  124,
      125,  125,  126,  126,  127,  128,  129,  130,  131,  132,
      133,  134,  135,  136,  137,  138,  140,  141,  142,  143,
      144,  145,  146,  147,  148,  148,  148,  149,  150,  151,
      151,  151,  151,  152,  153,  154,  155,  156,  156,  157,

      158,  159,  160,  161,  162,  163,  165,  167,  168,  169,
      170,  171,  172,  172,  172,  173,  174,  174,  174,  175,
      175,  176,  177,  177,  177,  177,  178,  180,  181,  182,
      184,  185,  186,  187,  188,  189,  191,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  193,  195,  197,
      198,  199,  201,  202,  203,  204,  206,  206,  206,  206,
      206,  206,  207,  207,  207,  208,  209,  210,  212,  214,
      216,  217,  218,  218,  218,  219,  220,  222,  223,  225,
      225
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   20,   20,    1,   21,   22,
       23,   24,   25,    1,   26,   26,   26,   26,   27,   28,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   30,
       29,   29,   29,   29,   29,   29,   29,   31,   29,   29,
       32,   33,   34,    1,   35,    1,   36,   37,   38,   39,

       40,   41,   29,   42,   43,   29,   44,   45,   29,   46,
       47,   48,   29,   49,   50,   51,   52,   53,   54,   55,
       56,   29,   57,   58,   59,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[60] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    1,    3,    1,
        1,    1,    1,    1,    1,    4,    1,    5,    5,    5,
        1,    1,    1,    1,    3,    5,    5,    5,    6,    7,
        6,    1,    3,    1,    6,    8,    8,    5,    5,    5,
        5,    6,    6,    6,    6,    9,    6,    7,    9,    6,
        9,    6,    9,    6,    6,    6,    1,    1,    1
    } ;

static yyconst short int yy_base[194] =
    {   0,
        0,    0,  430,  431,  431,  431,  406,   55,   22,  431,
      420,   53,  431,  431,  431,  414,  431,   48,   48,   52,
       58,   63,  431,  403,  402,  401,    0,  431,  431,  374,
       28,   39,   26,   46,  382,  370,  364,  372,  376,  431,
      359,  431,  431,   75,  431,   86,  376,  369,  431,  405,
      404,  403,  431,  431,  431,   77,   89,    0,   96,  111,
      123,  134,  395,  139,  431,  431,  431,    0,  370,  373,
      362,  357,  344,  336,  333,    0,  310,  309,  301,  289,
      293,  292,  431,   88,  293,  282,  431,  152,  431,   90,
      108,  296,    0,  158,  169,  172,  176,    0,   96,  271,

      256,   49,  264,  263,  266,    0,    0,  249,  248,  259,
      259,  252,  252,  249,  183,  187,  116,  123,  431,  275,
      201,  207,  116,  126,  218,  247,    0,  239,  236,    0,
      202,  199,  194,  202,  195,    0,  192,  176,  164,  156,
      197,  206,  226,  182,  234,   91,  237,    0,    0,  162,
      137,    0,  135,  118,  121,    0,  120,  109,  246,  247,
      242,  248,  262,  251,  265,  431,   93,    0,    0,    0,
       93,  431,   92,  254,  268,   82,    0,  431,    0,  431,
      309,  318,  323,  330,  339,  348,  354,  362,  371,  376,
      384,  389,  397

    } ;

static yyconst short int yy_def[194] =
    {   0,
      180,    1,  180,  180,  180,  180,  180,  181,  180,  180,
      180,  182,  180,  180,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  180,  180,  180,  183,  180,  180,  183,
      183,  183,  183,  183,  183,  183,  183,  183,  183,  180,
      180,  180,  180,  181,  180,  181,  180,  180,  180,  180,
      180,  184,  180,  180,  180,  180,  185,  186,  180,  180,
      180,  180,  187,  180,  180,  180,  180,  183,  183,  183,
      183,  183,  183,  183,  183,  183,  183,  183,  183,  183,
      183,  183,  180,  181,  180,  180,  180,  180,  180,  185,
      188,  189,  186,  180,  180,  180,  180,  190,  187,  183,

      183,  183,  183,  183,  183,  183,  183,  183,  183,  183,
      183,  183,  180,  180,  180,  180,  191,  188,  180,  180,
      180,  180,  190,  192,  180,  183,  183,  183,  183,  183,
      183,  183,  183,  183,  183,  183,  183,  180,  180,  191,
      193,  193,  180,  192,  180,  180,  180,  183,  183,  183,
      183,  183,  183,  183,  183,  183,  180,  180,  193,  193,
      180,  180,  180,  180,  180,  180,  183,  183,  183,  183,
      183,  180,  180,  180,  180,  183,  183,  180,  183,    0,
      180,  180,  180,  180,  180,  180,  180,  180,  180,  180,
      180,  180,  180

    } ;

static yyconst short int yy_nxt[491] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   22,
       23,   24,   25,   26,    4,   27,   27,   27,   27,   27,
       27,   28,    4,   29,   27,   27,   30,   31,   27,   32,
       33,   27,   34,   27,   27,   27,   27,   27,   35,   36,
       37,   27,   38,   39,   27,   27,   40,   41,   42,   45,
       47,   51,   54,   57,   48,   56,   56,   56,   58,   70,
       74,   55,   75,   59,   71,   60,   60,   61,   59,   45,
       64,   64,   64,   72,   62,   52,   76,   46,   63,   62,
       84,   77,   45,   73,   56,   56,   56,   62,  128,  129,

       91,   91,   62,   88,   89,   92,  117,   46,  147,  147,
      147,  124,   63,   94,   94,   94,   88,   89,   46,   91,
       46,  179,   95,   89,  119,  125,   59,  141,   60,   60,
       61,  178,  117,  177,   91,   95,   89,   62,   59,  142,
       61,   61,   61,  125,  176,  143,   96,  173,   96,   62,
       62,   97,   97,   97,   59,  145,   64,   64,   64,  172,
      171,   89,   62,  143,  115,   62,  115,  141,  170,  116,
      116,  116,  117,  145,   89,   94,   94,   94,   62,   89,
      169,  121,  168,  121,   62,   89,  122,  122,  122,   97,
       97,   97,   89,   97,   97,   97,   89,   62,   89,   89,

      116,  116,  116,   89,  116,  116,  116,  167,  160,   89,
       89,  163,   89,  119,   89,  158,   89,  141,  122,  122,
      122,  157,  142,   89,  122,  122,  122,   89,   89,  163,
      146,  156,  146,  155,   89,  147,  147,  147,  161,  154,
      161,   89,  153,  162,  162,  162,  164,   89,  164,  152,
      151,  165,  165,  165,  147,  147,  147,  141,  160,  162,
      162,  162,  142,  180,  166,  162,  162,  162,  165,  165,
      165,  175,  175,  175,  174,  166,  174,  166,  150,  175,
      175,  175,  165,  165,  165,  175,  175,  175,  166,  149,
      148,  119,  166,  139,  138,  166,  137,  136,  135,  134,

      133,  132,  131,  130,  127,  166,  126,  120,  166,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   50,  114,
       50,   50,   50,   50,   50,   50,   50,   68,   68,   68,
       68,   68,   50,  113,  112,  111,  110,   50,   50,   90,
       90,   90,   90,   90,   90,   90,   90,   90,   93,  109,
       93,   93,   93,   93,   93,   93,   93,   99,   99,  108,
      107,   99,  118,  118,  118,  118,  118,  118,  118,  118,
      118,   92,   92,   92,   92,   92,   92,   92,   92,   92,
      123,  106,  105,  123,  140,  140,  140,  140,  140,  140,
      140,  140,  140,  144,  104,  144,  144,  159,  159,  159,

      159,  159,  159,  159,  159,  159,  103,  102,  101,  100,
       98,   51,   87,   87,   86,   85,   83,   82,   81,   80,
       79,   78,   69,   67,   66,   65,   53,   49,   43,  180,
        3,  180,  180,  180,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  180,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  180,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  180,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  180,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  180,  180,  180,  180,  180,  180,  180
    } ;

static yyconst short int yy_chk[491] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    8,
        9,   12,   18,   20,    9,   19,   19,   19,   20,   31,
       33,   18,   33,   21,   31,   21,   21,   21,   22,   44,
       22,   22,   22,   32,   21,   12,   34,    8,   21,   22,
       46,   34,   84,   32,   56,   56,   56,   21,  102,  102,

       57,   90,   22,   56,   56,   57,   90,   44,  146,  146,
      146,   99,   21,   59,   59,   59,   56,   56,   46,   91,
       84,  176,   59,   59,   91,   99,   60,  117,   60,   60,
       60,  173,  117,  171,  118,   59,   59,   60,   61,  118,
       61,   61,   61,   99,  167,  123,   62,  158,   62,   61,
       60,   62,   62,   62,   64,  124,   64,   64,   64,  157,
      155,   62,   61,  123,   88,   64,   88,  140,  154,   88,
       88,   88,  140,  124,   62,   94,   94,   94,   64,   88,
      153,   95,  151,   95,   94,   94,   95,   95,   95,   96,
       96,   96,   88,   97,   97,   97,   95,   94,   94,   96,

      115,  115,  115,   97,  116,  116,  116,  150,  141,   95,
      115,  144,   96,  141,  116,  139,   97,  142,  121,  121,
      121,  138,  142,  115,  122,  122,  122,  116,  121,  144,
      125,  137,  125,  135,  122,  125,  125,  125,  143,  134,
      143,  121,  133,  143,  143,  143,  145,  122,  145,  132,
      131,  145,  145,  145,  147,  147,  147,  159,  160,  161,
      161,  161,  159,  160,  147,  162,  162,  162,  164,  164,
      164,  174,  174,  174,  163,  162,  163,  147,  129,  163,
      163,  163,  165,  165,  165,  175,  175,  175,  162,  128,
      126,  120,  165,  114,  113,  175,  112,  111,  110,  109,

      108,  105,  104,  103,  101,  165,  100,   92,  175,  181,
      181,  181,  181,  181,  181,  181,  181,  181,  182,   86,
      182,  182,  182,  182,  182,  182,  182,  183,  183,  183,
      183,  183,  184,   85,   82,   81,   80,  184,  184,  185,
      185,  185,  185,  185,  185,  185,  185,  185,  186,   79,
      186,  186,  186,  186,  186,  186,  186,  187,  187,   78,
       77,  187,  188,  188,  188,  188,  188,  188,  188,  188,
      188,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      190,   75,   74,  190,  191,  191,  191,  191,  191,  191,
      191,  191,  191,  192,   73,  192,  192,  193,  193,  193,

      193,  193,  193,  193,  193,  193,   72,   71,   70,   69,
       63,   52,   51,   50,   48,   47,   41,   39,   38,   37,
       36,   35,   30,   26,   25,   24,   16,   11,    7,    3,
      180,  180,  180,  180,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  180,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  180,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  180,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  180,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  180,  180,  180,  180,  180,  180,  180
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "src/lex.l"
#define INITIAL 0
#line 2 "src/lex.l"
#include <ext.h>
#define DEBUG 0
#define YY_USER_ACTION yylloc.first_line=yylloc.last_line=yylineno;\
                        yylloc.first_column=yycolumn;\
                        yylloc.last_column=yycolumn+yyleng-1; yycolumn+=yyleng;

int yycolumn = 1;
int level = 0;

void formatPrint(int line, const char* token, char* val) {
    if (DEBUG == 1) 
    {
        if (strcmp(token, "ERROR") == 0)
            printf("\033[31m<line:%3d, token:%-10s, val:%s\n\033[0m", line, token, val);
        else if (strcmp(token, "SGPS") == 0)
            printf("\033[35m<line:%3d, token:%-10s, val:%s\n\033[0m", line, token, "ignore");
        else if (strcmp(token, "DBPS") == 0)
            printf("\033[35m<line:%3d, token:%-10s, val:%s\n\033[0m", line, token, "ignore");
        else
            printf("\033[32m<line:%3d, token:%-10s, val:%s\n\033[0m", line, token, val);
    }
}
void setToken(int type, char*val) {
    Node *node = createNode(type, val, yylineno, level, 0);
    if (DEBUG)
    {
        printNode(node, 0);
        deleteNode(node);
    } else
    {
        yylval.node = node;
    }
}
/* 子结构 */
/* float的四种情况，小数点，e */
/* 三种情况，小数点，正常 */
/* 识别token */
/* 大写为关键字 */
/* ------------------------------------------------------------------------------------------------------------------------ */
#line 613 "src/flex.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 66 "src/lex.l"

#line 766 "src/flex.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 181 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 431 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 67 "src/lex.l"
{formatPrint(yylineno, "SGPS", yytext);}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 68 "src/lex.l"
{formatPrint(yylineno, "DBPS", yytext);}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 69 "src/lex.l"
{formatPrint(yylineno, "int", yytext);setToken(INT, yytext);if (!DEBUG) return INT;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 70 "src/lex.l"
{formatPrint(yylineno, "float", yytext);setToken(FLOAT, yytext);if (!DEBUG)return FLOAT;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 71 "src/lex.l"
{formatPrint(yylineno, "char", yytext);setToken(CHAR, yytext);if (!DEBUG)return CHAR;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 72 "src/lex.l"
{formatPrint(yylineno, "oct", yytext);setToken(OCT, yytext);if (!DEBUG)return FLOAT;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 73 "src/lex.l"
{formatPrint(yylineno, "hex", yytext);setToken(HEX, yytext);if (!DEBUG)return FLOAT;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 74 "src/lex.l"
{formatPrint(yylineno, "string", yytext);setToken(STRING, yytext);if (!DEBUG)return STRING;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 75 "src/lex.l"
{formatPrint(yylineno, "KW_const", yytext);setToken(KW_CONST, NULL);if (!DEBUG)return KW_CONST;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 76 "src/lex.l"
{formatPrint(yylineno, "KW_extern", yytext);setToken(KW_EXTERN, NULL);if (!DEBUG)return KW_EXTERN;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 77 "src/lex.l"
{formatPrint(yylineno, "KW_void", yytext);setToken(KW_VOID, NULL);if (!DEBUG)return KW_VOID;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 78 "src/lex.l"
{formatPrint(yylineno, "KW_int", yytext);setToken(KW_INT, NULL);if (!DEBUG)return KW_INT;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 79 "src/lex.l"
{formatPrint(yylineno, "KW_float", yytext);setToken(KW_FLOAT, NULL);if (!DEBUG)return KW_FLOAT;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 80 "src/lex.l"
{formatPrint(yylineno, "KW_char", yytext);setToken(KW_CHAR, NULL);if (!DEBUG)return KW_CHAR;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 81 "src/lex.l"
{formatPrint(yylineno, "KW_return", yytext);setToken(KW_RETURN, NULL);if (!DEBUG)return KW_RETURN;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 82 "src/lex.l"
{formatPrint(yylineno, "KW_if", yytext);setToken(KW_IF, NULL);if (!DEBUG)return KW_IF;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 83 "src/lex.l"
{formatPrint(yylineno, "KW_else", yytext);setToken(KW_ELSE, NULL);if (!DEBUG)return KW_ELSE;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 84 "src/lex.l"
{formatPrint(yylineno, "KW_while", yytext);setToken(KW_WHILE, NULL);if (!DEBUG)return KW_WHILE;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 85 "src/lex.l"
{formatPrint(yylineno, "KW_for", yytext);setToken(KW_FOR, NULL);if (!DEBUG)return KW_FOR;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 86 "src/lex.l"
{formatPrint(yylineno, "KW_break", yytext);setToken(KW_BREAK, NULL);if (!DEBUG)return KW_BREAK;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 87 "src/lex.l"
{formatPrint(yylineno, "KW_continue", yytext);setToken(KW_CONTINUE, NULL);if (!DEBUG)return KW_CONTINUE;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 88 "src/lex.l"
{formatPrint(yylineno, "KW_typedef", yytext);setToken(KW_TYPEDEF, NULL);if (!DEBUG)return KW_TYPEDEF;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 89 "src/lex.l"
{formatPrint(yylineno, "KW_struct", yytext);setToken(KW_STRUCT, NULL);if (!DEBUG)return KW_STRUCT;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 90 "src/lex.l"
{formatPrint(yylineno, "ID", yytext);setToken(ID, yytext);if (!DEBUG)return ID;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 91 "src/lex.l"
{formatPrint(yylineno, "SEMI", yytext);setToken(SEMI, NULL);if (!DEBUG)return SEMI;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 92 "src/lex.l"
{formatPrint(yylineno, "COMMA", yytext);setToken(COMMA, NULL);if (!DEBUG)return COMMA;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 93 "src/lex.l"
{formatPrint(yylineno, "GREATER", yytext);setToken(GREATER, yytext);if (!DEBUG)return GREATER;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 94 "src/lex.l"
{formatPrint(yylineno, "SMALLER", yytext);setToken(SMALLER, yytext);if (!DEBUG)return SMALLER;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 95 "src/lex.l"
{formatPrint(yylineno, "GREATER_EQUAL", yytext);setToken(GREATER_EQUAL, yytext);if (!DEBUG)return GREATER_EQUAL;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 96 "src/lex.l"
{formatPrint(yylineno, "SMALLER_EQUAL", yytext);setToken(SMALLER_EQUAL, yytext);if (!DEBUG)return SMALLER_EQUAL;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 97 "src/lex.l"
{formatPrint(yylineno, "EQUAL", yytext);setToken(EQUAL, yytext);if (!DEBUG)return EQUAL;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 98 "src/lex.l"
{formatPrint(yylineno, "NOT_EQUAL", yytext);setToken(NOT_EQUAL, yytext);if (!DEBUG)return NOT_EQUAL;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 99 "src/lex.l"
{formatPrint(yylineno, "ASSIGNOP", yytext);setToken(ASSIGN, NULL);if (!DEBUG)return ASSIGN;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 100 "src/lex.l"
{formatPrint(yylineno, "PLUS", yytext);setToken(PLUS, NULL);if (!DEBUG)return PLUS;}		
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 101 "src/lex.l"
{formatPrint(yylineno, "MINUS", yytext);setToken(MINUS, NULL);if (!DEBUG)return MINUS;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 102 "src/lex.l"
{formatPrint(yylineno, "DELIVERY", yytext);setToken(DELIVERY, NULL);if (!DEBUG)return DELIVERY;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 103 "src/lex.l"
{formatPrint(yylineno, "DPLUS", yytext);setToken(DPLUS, NULL);if (!DEBUG)return DPLUS;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 104 "src/lex.l"
{formatPrint(yylineno, "DMINUS", yytext);setToken(DMINUS, NULL);if (!DEBUG)return DMINUS;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 105 "src/lex.l"
{formatPrint(yylineno, "STAR", yytext);setToken(STAR, NULL);if (!DEBUG)return STAR;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 106 "src/lex.l"
{formatPrint(yylineno, "SAND", yytext);setToken(SAND, NULL);if (!DEBUG)return SAND;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 107 "src/lex.l"
{formatPrint(yylineno, "DIV", yytext);setToken(DIV, NULL);if (!DEBUG)return DIV;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 108 "src/lex.l"
{formatPrint(yylineno, "AND", yytext);setToken(AND, NULL);if (!DEBUG)return AND;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 109 "src/lex.l"
{formatPrint(yylineno, "OR", yytext);setToken(OR, NULL);if (!DEBUG)return OR;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 110 "src/lex.l"
{formatPrint(yylineno, "NOT", yytext);setToken(NOT, NULL);if (!DEBUG)return NOT;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 111 "src/lex.l"
{formatPrint(yylineno, "LP", yytext);setToken(LP, NULL);if (!DEBUG)return LP;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 112 "src/lex.l"
{formatPrint(yylineno, "RP", yytext);setToken(RP, NULL);if (!DEBUG)return RP;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 113 "src/lex.l"
{formatPrint(yylineno, "LC", yytext);setToken(LC, NULL);level++;if (!DEBUG)return LC;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 114 "src/lex.l"
{formatPrint(yylineno, "RC", yytext);setToken(RC, NULL);level--;if (!DEBUG)return RC;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 115 "src/lex.l"
{formatPrint(yylineno, "LB", yytext);setToken(LB, NULL);if (!DEBUG)return LB;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 116 "src/lex.l"
{formatPrint(yylineno, "RB", yytext);setToken(RB, NULL);if (!DEBUG)return RB;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 117 "src/lex.l"
{formatPrint(yylineno, "DOT", yytext);setToken(DOT, NULL);if (!DEBUG)return DOT;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 118 "src/lex.l"
{formatPrint(yylineno, "POINTER", yytext);setToken(POINTER, NULL);if (!DEBUG)return POINTER;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 119 "src/lex.l"
{formatPrint(yylineno, "#include", yytext);setToken(INCLUDE, NULL);if (!DEBUG)return INCLUDE;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 120 "src/lex.l"
{formatPrint(yylineno, "#define", yytext);setToken(DEFINE, NULL);if (!DEBUG)return DEFINE;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 121 "src/lex.l"
{yycolumn=1;}   
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 122 "src/lex.l"
{}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 123 "src/lex.l"
{formatPrint(yylineno, "ERROR", yytext);}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 124 "src/lex.l"
ECHO;
	YY_BREAK
#line 1147 "src/flex.c"
			case YY_STATE_EOF(INITIAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 181 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 181 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 180);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 124 "src/lex.l"

